services:
  backend:
    build: ./backend
    container_name: calculator-backend
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: calculator-frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
