apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
  namespace: flask  
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers: 
      - name: backend-container
        image: mrkhadus/calculator-backend:6295952a0395579ecf7afa7cbc836d76d9376c3c
        ports:
        - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
  namespace: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: mrkhadus/calculator-frontend:6295952a0395579ecf7afa7cbc836d76d9376c3c
        env:
          - name: BACKEND_URL
            value: "http://backend-service:5001"
        ports:
        - containerPort: 8000
